In [1]:
import pandas as pd

df = pd.read_csv("../data_processed/master_test_dataset.csv")

In [2]:
team1_df = df.copy()

team1_df["country"] = team1_df["team1"]
team1_df["opponent"] = team1_df["team2"]

In [3]:
def get_result_team1(row):

    if pd.isna(row["winner"]):
        return "Draw"

    elif row["winner"] == row["team1"]:
        return "Win"

    else:
        return "Loss"

team1_df["result"] = team1_df.apply(get_result_team1, axis=1)

In [4]:
def get_location_team1(row):

    if row["home_team"] == row["team1"]:
        return "Home"

    elif row["away_team"] == row["team1"]:
        return "Away"

    else:
        return "Neutral"

team1_df["location"] = team1_df.apply(get_location_team1, axis=1)

In [5]:
team2_df = df.copy()

team2_df["country"] = team2_df["team2"]
team2_df["opponent"] = team2_df["team1"]

In [6]:
def get_location_team2(row):

    if row["home_team"] == row["team2"]:
        return "Home"

    elif row["away_team"] == row["team2"]:
        return "Away"

    else:
        return "Neutral"

team2_df["location"] = team2_df.apply(get_location_team2, axis=1)

In [7]:
final_df = pd.concat(
    [team1_df, team2_df],
    ignore_index=True
)

In [8]:
final_df[
    ["team1", "team2", "country",
     "opponent", "result", "location"]
].head(10)

         team1         team2      country      opponent result location
0    Australia  South Africa    Australia  South Africa   Loss     Home
1    Australia  South Africa    Australia  South Africa   Loss     Home
2    Australia  South Africa    Australia  South Africa    Win     Home
3    Australia      Pakistan    Australia      Pakistan    Win     Home
4    Australia      Pakistan    Australia      Pakistan    Win     Home
5    Australia      Pakistan    Australia      Pakistan    Win     Home
6  New Zealand    Bangladesh  New Zealand    Bangladesh    Win     Home
7  New Zealand    Bangladesh  New Zealand    Bangladesh    Win     Home
8  New Zealand      Pakistan  New Zealand      Pakistan    Win     Home
9  New Zealand      Pakistan  New Zealand      Pakistan    Win     Home

In [9]:
final_df.to_csv(
    "../data_processed/team_view_dataset.csv",
    index=False
)

In [10]:
final_df.groupby(["country", "result"]).size()

country       result
Australia     Draw      21
              Loss      24
              Win       74
Bangladesh    Draw      11
              Loss      40
              Win       13
England       Draw      28
              Loss      49
              Win       72
India         Draw      24
              Loss      19
              Win       66
Ireland       Loss       5
              Win        1
New Zealand   Draw      20
              Loss      23
              Win       40
Pakistan      Draw      15
              Loss      18
              Win       18
South Africa  Draw      13
              Loss      33
              Win       60
Sri Lanka     Draw      17
              Loss      28
              Win       40
West Indies   Draw      16
              Loss      38
              Win       23
Zimbabwe      Draw       2
              Loss      22
              Win        4
dtype: int64

In [11]:
final_df[final_df["country"] == "Australia"]["result"].value_counts()

result
Win     74
Loss    24
Draw    21
Name: count, dtype: int64

In [12]:
final_df[
    ["country", "winner", "result"]
].sample(20)

           country        winner result
676        England       England    Win
450        England       England    Win
1098  South Africa  South Africa    NaN
828   South Africa       England   Loss
1029       England   New Zealand    NaN
962      Sri Lanka           NaN    NaN
392    New Zealand   New Zealand    Win
16     West Indies           NaN   Draw
1481      Pakistan           NaN    NaN
250      Australia     Australia    Win
106          India         India    Win
1146     Australia       England    NaN
75           India       England   Loss
1729  South Africa         India    NaN
690      Australia  South Africa   Loss
1274         India         India    NaN
1150   New Zealand           NaN    NaN
1305   West Indies           NaN    NaN
1220       England      Pakistan    NaN
472        England           NaN   Draw

In [13]:
for col in ["team1", "team2", "winner"]:
    final_df[col] = final_df[col].astype(str).str.strip()

In [14]:
def get_result_team1(row):

    if row["winner"] == "nan":
        return "Draw"

    elif row["winner"] == row["team1"]:
        return "Win"

    else:
        return "Loss"

In [15]:
def get_result_team2(row):

    if row["winner"] == "nan":
        return "Draw"

    elif row["winner"] == row["team2"]:
        return "Win"

    else:
        return "Loss"

In [16]:
team1_df["result"] = team1_df.apply(get_result_team1, axis=1)

team2_df["result"] = team2_df.apply(get_result_team2, axis=1)

In [17]:
final_df = pd.concat(
    [team1_df, team2_df],
    ignore_index=True
)

In [18]:
final_df["result"].value_counts()

result
Loss    1044
Win      710
Name: count, dtype: int64

In [19]:
final_df.to_csv(
    "../data_processed/team_view_dataset.csv",
    index=False
)

In [20]:
df = pd.read_csv("../data_processed/master_test_dataset.csv")

In [21]:
for col in ["team1", "team2"]:
    df[col] = df[col].str.strip()

df["winner"] = df["winner"].str.strip()

In [22]:
team1_df = df.copy()

team1_df["country"] = team1_df["team1"]
team1_df["opponent"] = team1_df["team2"]

In [23]:
def get_result_team1(row):

    if pd.isna(row["winner"]):
        return "Draw"

    elif row["winner"] == row["team1"]:
        return "Win"

    else:
        return "Loss"

In [24]:
team1_df["result"] = team1_df.apply(
    get_result_team1,
    axis=1
)

In [25]:
team2_df = df.copy()

team2_df["country"] = team2_df["team2"]
team2_df["opponent"] = team2_df["team1"]

In [26]:
def get_result_team2(row):

    if pd.isna(row["winner"]):
        return "Draw"

    elif row["winner"] == row["team2"]:
        return "Win"

    else:
        return "Loss"

In [27]:
team2_df["result"] = team2_df.apply(
    get_result_team2,
    axis=1
)

In [28]:
final_df = pd.concat(
    [team1_df, team2_df],
    ignore_index=True
)

In [29]:
final_df["result"].value_counts()

result
Loss    710
Win     710
Draw    334
Name: count, dtype: int64

In [30]:
final_df.to_csv(
    "../data_processed/team_view_dataset.csv",
    index=False
)

In [31]:
def get_location_team1(row):

    if row["home_team"] == row["team1"]:
        return "Home"

    elif row["away_team"] == row["team1"]:
        return "Away"

    else:
        return "Neutral"

In [32]:
team1_df["location"] = team1_df.apply(
    get_location_team1,
    axis=1
)

In [33]:
def get_location_team2(row):

    if row["home_team"] == row["team2"]:
        return "Home"

    elif row["away_team"] == row["team2"]:
        return "Away"

    else:
        return "Neutral"

In [34]:
team2_df["location"] = team2_df.apply(
    get_location_team2,
    axis=1
)

In [35]:
final_df.columns

Index(['match_id', 'team1', 'team2', 'venue', 'city', 'date', 'winner',
       'win_by_runs', 'win_by_wickets', 'year', 'result_type', 'host_country',
       'home_team', 'away_team', 'opponent', 'country', 'result'],
      dtype='object')

In [36]:
final_df.to_csv(
    "../data_processed/team_view_dataset.csv",
    index=False
)

In [37]:
def get_location_team1(row):

    if row["home_team"] == row["team1"]:
        return "Home"

    elif row["away_team"] == row["team1"]:
        return "Away"

    else:
        return "Neutral"

In [38]:
team1_df["location"] = team1_df.apply(
    get_location_team1,
    axis=1
)

In [39]:
def get_location_team2(row):

    if row["home_team"] == row["team2"]:
        return "Home"

    elif row["away_team"] == row["team2"]:
        return "Away"

    else:
        return "Neutral"

In [40]:
team2_df["location"] = team2_df.apply(
    get_location_team2,
    axis=1
)

In [41]:
final_df

,match_id,team1,team2,venue,city,date,winner,win_by_runs,win_by_wickets,year,result_type,host_country,home_team,away_team,opponent,country,result
0,1000851,Australia,South Africa,Western Australia Cricket Association Ground,Perth,2016-11-03,South Africa,177.0,NaN,2016,Win,Australia,Australia,South Africa,South Africa,Australia,Loss
1,1000853,Australia,South Africa,Bellerive Oval,Hobart,2016-11-12,South Africa,80.0,NaN,2016,Win,Australia,Australia,South Africa,South Africa,Australia,Loss
2,1000855,Australia,South Africa,Adelaide Oval,Adelaide,2016-11-24,Australia,NaN,7.0,2016,Win,Australia,Australia,South Africa,South Africa,Australia,Win
3,1000881,Australia,Pakistan,"Brisbane Cricket Ground, Woolloongabba",Brisbane,2016-12-15,Australia,39.0,NaN,2016,Win,Australia,Australia,Pakistan,Pakistan,Australia,Win
4,1000883,Australia,Pakistan,Melbourne Cricket Ground,Melbourne,2016-12-26,Australia,18.0,NaN,2016,Win,Australia,Australia,Pakistan,Pakistan,Australia,Win
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1749,936149,South Africa,Sri Lanka,Newlands,Cape Town,2017-01-02,South Africa,282.0,NaN,2017,Win,South Africa,South Africa,Sri Lanka,South Africa,Sri Lanka,Loss
1750,936151,South Africa,Sri Lanka,New Wanderers Stadium,Johannesburg,2017-01-12,South Africa,118.0,NaN,2017,Win,South Africa,South Africa,Sri Lanka,South Africa,Sri Lanka,Loss
1751,995451,Sri Lanka,Australia,Pallekele International Cricket Stadium,Pallekele,2016-07-26,Sri Lanka,106.0,NaN,2016,Win,Sri Lanka,Sri Lanka,Australia,Sri Lanka,Australia,Loss
1752,995453,Sri Lanka,Australia,Galle International Stadium,Galle,2016-08-04,Sri Lanka,229.0,NaN,2016,Win,Sri Lanka,Sri Lanka,Australia,Sri Lanka,Australia,Loss
1753,995455,Sri Lanka,Australia,Sinhalese Sports Club Ground,Colombo,2016-08-13,Sri Lanka,163.0,NaN,2016,Win,Sri Lanka,Sri Lanka,Australia,Sri Lanka,Australia,Loss

In [42]:
final_df = pd.concat(
    [team1_df, team2_df],
    ignore_index=True
)

In [43]:
final_df.columns

Index(['match_id', 'team1', 'team2', 'venue', 'city', 'date', 'winner',
       'win_by_runs', 'win_by_wickets', 'year', 'result_type', 'host_country',
       'home_team', 'away_team', 'opponent', 'country', 'result', 'location'],
      dtype='object')

In [44]:
final_df.to_csv(
    "../data_processed/team_view_dataset.csv",
    index=False
)

In [45]:
sena_countries = [
    "South Africa",
    "England",
    "New Zealand",
    "Australia"
]

In [46]:
final_df["is_sena"] = (
    (final_df["host_country"].isin(sena_countries)) &
    (final_df["location"] == "Away")
)

In [47]:
final_df["sena_type"] = final_df["is_sena"].map({
    True: "SENA",
    False: "Non-SENA"
})

In [48]:
final_df.to_csv(
    "../data_processed/team_view_dataset.csv",
    index=False
)

In [49]:
final_df.columns

Index(['match_id', 'team1', 'team2', 'venue', 'city', 'date', 'winner',
       'win_by_runs', 'win_by_wickets', 'year', 'result_type', 'host_country',
       'home_team', 'away_team', 'opponent', 'country', 'result', 'location',
       'is_sena', 'sena_type'],
      dtype='object')

In [50]:
final_df["sena_type"] = final_df["is_sena"].map({
    True: "SENA",
    False: "Non-SENA"
})

In [51]:
final_df["sena_type"].value_counts()

sena_type
Non-SENA    1314
SENA         440
Name: count, dtype: int64

In [52]:
final_df.to_csv(
    "../data_processed/team_view_dataset.csv",
    index=False
)

In [53]:
final_df[
    final_df["country"] == "India"
][
    ["country", "opponent", "location", "host_country"]
].sample(20)

     country      opponent location host_country
984    India     Australia     Away    Australia
44     India     Australia     Home        India
528    India       England     Home        India
76     India       England     Away      England
1464   India     Sri Lanka     Away    Sri Lanka
431    India   West Indies     Away  West Indies
745    India     Australia     Home        India
1486   India       England     Away      England
67     India     Sri Lanka     Away    Sri Lanka
1032   India   New Zealand     Away  New Zealand
735    India     Australia     Away    Australia
1155   India     Australia     Home        India
963    India     Sri Lanka     Home        India
191    India       England     Home        India
318    India     Australia     Away    Australia
1507   India     Australia     Away    Australia
350    India       England     Away      England
1458   India    Bangladesh     Away   Bangladesh
148    India  South Africa     Home        India
1492   India   West Indies     Away  West Indies